language: node_js
node_js:
  - node
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: JXK9eApqYwokjlDv2lccVNEjN8bgaEASGec9rAOKp+SLrKqjR1zGRKvZlPLGV6NkBLJ4XizQwm6hrOE+Ttdxz6AfJ801KP766j9Rxa1BbrD1pHOZOKb3VA6Isc0vaiTuY5rS/CztBuXviK72ZBxji7gsVbugLMTT3RkgFFv663Y7cSBENC45UBPlzfPqK4/AustpAUgR/xDxZhuXZyaDXkl+XZjloYJKU4C2YO193+yUjYWWEwNtYQlD0uTw7IAJhAUadxmB1BBMUWvtaCDLqQZsJqdyfLf/a25+XXKUgAS6/PsYRkA93hIPhKoruP2p6SGA2dHC9Hq02LC2Tgcsh46tzoGsPUiPQKFSfCkK1nzPEeMPpfsaI9gGuM+8rJOQ7WpC9yBWEdCITSAZX4gNc6zD4xrGFipkvLIyGlkbr4ik9UrYVkQeZQ49xy7zA6M2ypsqpj/XaXBLbxVJsCqevPITy20UA3uKv+uCwDUdMWQJuUerP/eOeqmqCXF5Jz//74ytcFeivcj3IOT8hbkJIq7NOLTYPHQGAaqSTssKhx0lzDrj5Yc3lRaZeqRLx67dd3FSxlFq2GgeVS2pTA0Gs/Z13wt4S4c8LCHnILgvNe+CMugcqq0HtXNrWk8XR0iFndwckS9KMrFUw8YuWJtZWK1+LYktClAaT02jjtQgAGY=
app: septa-view
